config/routes.rb
Rails.application.routes.draw do
  get 'reports/index'
  get 'reports', to: "reports#index"
  get 'reports/external'
  resources :repositories
  resources :profiles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :username, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9-]*\z/ }
  has_many :repositories, dependent: :destroy
  accepts_nested_attributes_for :repositories

end

app/models/repository.rb
class Repository < ApplicationRecord
  belongs_to :profile
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  def self.increment(path)
    view_count = ViewCount.find_or_create_by(path: path)
    self.increment_counter(:views, view_count.id, touch: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_view_count
  def set_view_count
    ViewCount.increment(request.path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /profiles or /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profile_url(@profile), notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.includes(:repositories).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.fetch(:profile, {}).permit(:username, repositories_attributes: [:name, :tags])
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Profile.all.includes(:repositories)
    if params[:tag].present?
      @reports = @reports.where('LOWER(repositories.tags) LIKE ?', ActiveRecord::Base.sanitize_sql("%#{params[:tag]}%").downcase).references(:repositories)
    end
  end

  def external
    @reports = ReportService.new.generate
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: %i[ show edit update destroy ]
  skip_before_action :verify_authenticity_token

  # GET /repositories or /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1 or /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories or /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully created." }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1 or /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to repository_url(@repository), notice: "Repository was successfully updated." }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1 or /repositories/1.json
  def destroy
    @repository.destroy

    respond_to do |format|
      format.html { redirect_to repositories_url, notice: "Repository was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def repository_params
      params.fetch(:repository, {}).permit(:name, :tags, :profile_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/home/index.html.erb
lala

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChallengeRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile) do |form| %>
  <% if profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :username, class: "form-label"%>
    <%= form.text_field :username, class: "form-control" %>
  </div>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>Username: <%= profile.username %></p>
</div>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Show this profile", @profile %> |
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Username</th>
      <th scope="col">SuperUser</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @profiles.each do |profile| %>

    <tr>
      <th scope="row"><%= profile.id %></th>
      <td><%= profile.username%></td>
      <td><%= profile.superuser %></td>
      <td> <%= link_to "Show this profile", profile, class: "btn btn-primary" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New profile", new_profile_path, class: "btn btn-primary" %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render "form", profile: @profile %>

<br>

<div>
  <%= link_to "Back to profiles", profiles_path %>
</div>

app/views/profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @profile %>

<div class="btn-group">
  <%= link_to "Edit this profile", edit_profile_path(@profile), class: "btn btn-secondary" %>
  <%= link_to "Back to profiles", profiles_path, class: "btn btn-primary" %>
  <%= button_to "Destroy this profile", @profile, method: :delete, class: "btn btn-danger" %>
</div>

app/views/reports/external.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Username</th>
      <th scope="col">Repositories</th>
    </tr>
  </thead>
  <tbody>
  <% @reports.each do |profile| %>

    <tr>
      <th scope="row"><%= profile.id %></th>
      <td><%= profile.username%></td>
      <td> 
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Tags</th>
                <th scope="col">Profile</th>
                </tr>
            </thead>
            <tbody>
            <% profile.repositories.each do |repository| %>

                <tr>
                <th scope="row"><%= repository.id %></th>
                <td><%= repository.name%></td>
                <td><%= repository.tags %></td>
                <td> <%= link_to repository.profile.username, repository.profile%></td>
                </tr>
            <% end %>
            </tbody>
        </table>  
    </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New profile", new_profile_path, class: "btn btn-primary" %>

app/views/reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Profiles</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Username</th>
      <th scope="col">Repositories</th>
    </tr>
  </thead>
  <tbody>
  <% @reports.each do |profile| %>

    <tr>
      <th scope="row"><%= profile.id %></th>
      <td><%= profile.username%></td>
      <td> 
      <% if profile.repositories.count > 0%>
        <table class="table">
            <thead>
                <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Tags</th>
                <th scope="col">Profile</th>
                </tr>
            </thead>
            <tbody>
            <% profile.repositories.each do |repository| %>

                <tr>
                <th scope="row"><%= repository.id %></th>
                <td><%= repository.name%></td>
                <td><%= repository.tags %></td>
                <td> <%= link_to repository.profile.username, repository.profile%></td>
                </tr>
            <% end %>
            </tbody>
        </table>  
        <% end %>
    </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New profile", new_profile_path, class: "btn btn-primary" %>

app/views/repositories/_form.html.erb
<%= form_with(model: repository) do |form| %>
  <% if repository.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
        <% repository.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="mb-3">
    <%= form.label :name, class: "form-label"%>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :tags, class: "form-label"%>
    <%= form.text_field :tags, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :profile_id, class: "form-label"%>
    <%= form.collection_select(:profile_id, Profile.all, :id, :username, {}, {class: "form-select"}) %>
  </div>
  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/repositories/_repository.html.erb
<div id="<%= dom_id repository %>">
    <p>Name: <%= repository.name%></p>
    <p>Tags: <%= repository.tags%></p>
    <p>Profile: <%= repository.profile.username%></p>
</div>

app/views/repositories/edit.html.erb
<h1>Editing repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Show this repository", @repository %> |
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/index.html.erb
<p style="color: green"><%= notice %></p>


<h1>Repositories</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Tags</th>
      <th scope="col">Profile</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @repositories.each do |repository| %>

    <tr>
      <th scope="row"><%= repository.id %></th>
      <td><%= repository.name%></td>
      <td><%= repository.tags %></td>
      <td> <%= link_to repository.profile.username, repository.profile%></td>
      <td> <%= link_to "Show this repository", repository, class: "btn btn-primary" %> </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "New repository", new_repository_path, class: "btn btn-primary"  %>

app/views/repositories/new.html.erb
<h1>New repository</h1>

<%= render "form", repository: @repository %>

<br>

<div>
  <%= link_to "Back to repositories", repositories_path %>
</div>

app/views/repositories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @repository %>

<div class="btn-group">
  <%= link_to "Edit this repository", edit_repository_path(@repository),  class: "btn btn-secondary" %>
  <%= link_to "Back to repositories", repositories_path, class: "btn btn-primary" %>

  <%= button_to "Destroy this repository", @repository, method: :delete, class: "btn btn-danger" %>
</div>